name: Catkin Make (Build and Test)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: eteration/muto-ros:noetic-desktop-full
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: |
          mkdir -p $(pwd)/tmp/muto/src/
          ln -s $(pwd) $(pwd)/tmp/muto/src/
          cd $(pwd)/tmp/muto
          catkin_make
          catkin_test
        name: Build in ros container
